library(MASS)
library(freqparcoord)
rand <- data.frame(replicate(10,sample(0:1000,1000,rep=TRUE)))
freqparcoord(rand,m=10,k=70)

data("mtcars")
freqparcoord(mtcars ,m=10,k=5)
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- factor(mtcars$am)
mtcars$gear <- factor(mtcars$gear)
mtcars$carb <- factor(mtcars$carb)
lmodel <- lm(mtcars$mpg ~ ., data=mtcars)
rlmodel<- stepAIC(lmodel)
summary(rlmodel)

parcoord( mtcars[,1:3], col=rainbow(length(mtcars[,1])), var.label=TRUE)
freqparcoord( mtcars[,1:3],m=8,k=4)